module_execution_type: "both"
sample_ids_file: "/home/icastro/workspace/phiflow-bash/samples.txt"
dataset_name: "test_results"
kraken2_db_path: "/home/icastro/databases/kraken2db/k2_pluspf_oct_2025"
host_genome_index_path: "/home/icastro/human_reference/indexes/STAR/hg_T2T"
host_genome_annotation_path_gtf: "/home/icastro/human_reference/T2T/GCF_009914755.1_T2T-CHM13v2.0_genomic.gtf"
host_genome_annotation_path_bed: "/home/icastro/human_reference/T2T/GCF_009914755.1_T2T-CHM13v2.0_genomic.bed"
paired_end: "yes"
strandness: "auto"
workdir: "/home/icastro/workspace/phiflow-bash"
samplesdir: "/home/icastro/workspace/transciptome_samples_test"
